# Generated by Django 2.2.1 on 2019-08-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produtor',
        ),
        migrations.AddField(
            model_name='produto',
            name='pausar',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produtor',
        ),
    ]
