# Generated by Django 2.2.1 on 2019-08-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0003_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
