# Generated by Django 2.2.1 on 2019-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0004_auto_20190819_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
