# Generated by Django 2.2.1 on 2019-08-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0005_auto_20190820_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
