# Generated by Django 2.2.1 on 2019-08-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0006_auto_20190821_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
