# Generated by Django 2.2.1 on 2019-08-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0008_auto_20190829_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='nome',
        ),
    ]
