# Generated by Django 2.2.1 on 2019-08-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0009_remove_usuarioperfil_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='user',
        ),
    ]
