# Generated by Django 2.2.1 on 2019-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0015_usuarioperfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pausar',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
