# Generated by Django 2.2.1 on 2019-09-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastrar', '0017_minhascompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='minhascompras',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
