# Generated by Django 2.2.1 on 2019-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0019_auto_20190919_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='celular',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='cidade',
            field=models.CharField(default=1, max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='endereco',
            field=models.CharField(default=1, max_length=50, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('PE', 'Pernambuco')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
