# Generated by Django 2.2.1 on 2019-09-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0020_auto_20190919_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='comprador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
