# Generated by Django 2.2.1 on 2019-10-01 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0021_auto_20190924_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='produto',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='celular',
            field=models.CharField(max_length=19, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
